name: graphpancake-docs
channels:
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python>=3.8
  - pip
  - pandas
  - numpy
  - torch
  - torchvision
  - torchaudio
  - pytorch-geometric
  - rdkit
  - networkx
  - matplotlib
  - plotly
  - pyyaml
  - tqdm
  - psutil
  - regex
  - sqlite
  - setuptools
  - setuptools-scm
  - versioningit
  - pip:
      - sphinx>=4.0
      - sphinx-rtd-theme
      - sphinx-autodoc-typehints
      - sphinx-design
      - myst-parser
      - shibuya

